### PR TITLE
Added option to store project with all settings (image settings, laser settings)

### PR DESCRIPTION
**Pull request by opitzh**
image
image
image
image
image

Actually no language translation included

### CODE REVIEW

**Comment by opitzh** [comment]
By the way: the image itself is also stored in the lps file

**Comment by arkypita** [comment]
Hi! This is a great +1 for LaserGRBL
Thanks for your code contribution.

I have done a little change to be able to open lpf from the standard "open file" menu, instead of using a new entry for "open project".

**Comment by arkypita** [comment]
Before adding to the main branch and release:

Do you think it is possible to save the project from the main form, instead of from image size form?
I don't like to have a popup each time i process the file, asking for save: i prefer a menu entry "save as project" that the user can push when and if he want. Do you think it is possible?

**Comment by arkypita** [comment]
Maybe not, because one can add multiple files... so only .nc is possible once processed. Any Idea?

**Comment by opitzh** [comment]
Thank you very much - you did a great work with this program and I really like it. I will have a look on it... I think it should be also possible: create a temp file if an image is processed and append new settings to the file if a new image is added... if the project is saved the file can be stored somewhere, otherwise the temp file is deleted if the program shuts down... I will try this within this week

**Comment by opitzh** [comment]
Hi, should work now also with multiple opened files and I removed the export dialog. Please check it out...
Project files can be opened from the main form:
image

And saved also via the main form:
image

**Pull request merged**
