### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by gmmanonymus111**
This PR should fix some minor issues:

- Jog to zero should now return to Z0 as well
- Data stuck in LaserGRBL buffer while using WiFi should be emptied now
- Arduino Mega buffer is corrected to be 255 bytes
- Update Hungarian translation
- Fixed Visual Studio warnings

### CODE REVIEW

**Comment by arkypita** [comment]
I'll take a look.

Please note that it was my choice that the Jog operated only on X and Y, and not Z. It was not a oversight.

**Comment by gmmanonymus111** [comment]
Thank you!
For the Z axis, I thougth it was a good idea since there is a minimal Z axis support. For anyone using it, it returns to Z0 as well, for users with X/Y only, it does nothing. In case it causes issues, it can be removed.

**Comment by sinfocomp** [comment]
I have xyz but no home sw on z, hope this helps, could be more like this setup

**Comment by gmmanonymus111** [comment]
@sinfocomp This upate should not modify homing, only jogging will return to Z0 (homing can be modified only by recompiling GRBL afaik)

**Comment by arkypita** [comment]
> For the Z axis, I thougth it was a good idea since there is a minimal Z axis support. For anyone using it, it returns to Z0 as well, for users with X/Y only, it does nothing. In case it causes issues, it can be removed.

My choice was to not restore Z to zero position because:
1) the "jog to home" button is conceptually inside the group of buttons that is used to jog X and Y
2) the Z axis is used for focusing, X/Y for positioning, so they fulfilling two very different tasks

I think that if you have done a fine focusing using Z control, and you loose it because of moving XY to home, you are not happy. I will remove this changes from code. 

Maybe if you think that is needed I can add a pushable "z home" button between Z up/down arrows. What do you think?

**Comment by arkypita** [comment]
I am sorry if I did not quickly implement your commit but I am quite busy and I see that a lot of users complain about problems (most of the time non-existent) every time I release a version, so I try to check every line of code modified by third parties to make sure of what I publish

**Comment by arkypita** [comment]
Can you tell me something about the `stuckBufferCounter ` procedure? 
What problem are you supposed to correct? How should its mechanism work?

```
private void ParseBf(string p)
{
	string bf = p.Substring(3, p.Length - 3);
	string[] ab = bf.Split(",".ToCharArray());

	mGrblBlocks = int.Parse(ab[0]);
	mGrblBuffer = int.Parse(ab[1]);

	if (stuckBufferCounter > 10 && mPending.Count > 0)
		ManageCommandResponse("ok");
	if (mGrblBuffer == BUFFER_SIZE && mPending.Count > 0)
		stuckBufferCounter++;
	if ((mGrblBuffer != BUFFER_SIZE) ||( mPending.Count == 0 && mGrblBuffer == BUFFER_SIZE))
		stuckBufferCounter = 0;

	EnlargeBuffer(mGrblBuffer);
}
```

**Comment by gmmanonymus111** [comment]
No problem at all, you can take your time, better safe than sorry :)

For the Z axis, if you think it is not needed, then you can remove it. I personally found it useful for multiple passes when laser is lowered for better cut (since I set the zero point with G92, it sets Z axis as well, then it returns to it's normal position, and the next piece of plank is ready to be cut without messing with focus setting). I wouldn't squeeze another button between the Z axis buttons, it would made it a bit of ugly IMO, and for a 'Z0' a custom button is enough.

I came up with the bufferCounter idea because almost every time I made a larger project over telnet, there were commands stuck in LaserGRBL's buffer, although they were sent to the Aruino, and Arduino executed it, but for some reason, the response never registered in LaserGRBL. When it happens only for a few (usually 1 or 2) lines of GCode, LaserGRBL hangs near the end of the job (manually sening 'ok' fixes it), but when there are more lines of GCode get stuck, LaserGRBL thinks Arduino's puffer is still full, and won't send new lines of code (this can be really annoying during a longer job, extending the time needed to finish). So, this piece of code should check Arduino's buffer if it's empty, and if there is some GCode in LaserGRBL's buffer, it mimics an 'ok' response to get rid of it. If Aruino reports there is an ongoing GCode execution, it should do nothing.
Most likely it will work only if buffer data is enabled within status reports, and needed only for wireless connection.

**Comment by arkypita** [comment]
> I personally found it useful for multiple passes when laser is lowered for better cut (since I set the zero point with G92, it sets Z axis as well, then it returns to it's normal position, and the next piece of plank is ready to be cut without messing with focus setting).

For this needs I think that you can customize header and footer to store the Z position with G92 when start and restore when the job is finished.

image

**Comment by arkypita** [comment]
Thanks for the explanation about the bufferCounter feature, looking at the code I had imagined that it was something like this.

Actually I think one should ask himself why he has this type of hang, because it is better to solve them at the root instead of chasing them with software solutions. It should not happen that responses or commands are lost or damaged in communication. However, the serial protocol provided by grbl does not provide for an error correction, therefore electrical disturbances can put it in crisis.

Right now I am running a simulation [in check mode](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#c---check-gcode-mode) which sets grbl to respond to commands but without executing them, that is, without moving the motors or turning on the laser.

It is streaming more than 9 milion of gcode line with a projected time of 3 hours (46860 line/min, 780 line/sec). I expect no error and no hang.

I am using buffered streaming mode, and ultra fast thread, that is the most stressing mode to test the communication. I am using WiFi with telnet too.

After that i'll repeat the test but without the check mode, so with motor moving (but i'll turn off the laser). I expect no error and no hang too, but this test it is really very different from the previous one, because the electric noise produced by the motors comes into play. I will let you know.

I am doing those test with my laptop on main floor of my home, and the engraver placed on the basement. In my opinion if the WiFi link is strong and stable the wireless connection is not the cause.

Imho 9 times out of ten the cause is serial communication, so in this case the one between arduino and the esp module. 

Tn this case my test is very particular since I use a board from robotdyn that combines arduino and esp in a single board, therefore very short and well-designed connections between them. I suggest it a lot!

https://robotdyn.com/uno-wifi-r3-atmega328p-esp8266-32mb-flash-usb-ttl-ch340g-micro-usb.html

image

**Comment by arkypita** [comment]
I suggest you to do a test similar to mine (with and without check mode) and try to intervene on the shielding of the cables between the Arduino and ESP tx rx serial

**Comment by StuartB4** [comment]
I like the look of that board. The only thing I don't like is because they got so much on it, they had to use a weak mini surface mounted USB socket. I prefer the older / bigger through hole socket. Easier to resolder if it does come loose.

**Comment by gmmanonymus111** [comment]
I'm already using that board, so it's one upgrade less ^^
Both my laptop and my cnc machine is in the same room as the router, so signal power should not be the problem here. I will check out the suggested test to see if any electrical noise may isturb my setup.

**Comment by gmmanonymus111** [comment]
So, I finished the testings.
I made 3 tests (on my uno+wifi with checkmode, and with normal mode, laser disconnected; and with a mega+wifi, here there was nothing connected to the mcu) with a 2-hour job, repeated 3 times.
The good news: all of the tests made some code stuck in LaserGRBL's buffer, at random times (mostly the last commands were there). It looks like electrical noise isn't the problem here
The bad news: Since electrical noise doesn't seem to have an impact on the communication, I might have to reconfigure my wireless network (or be lazy and sync with GRBL's status report 😄)

**Pull request merged**
