### PR TITLE
Add rudimentary color filter option for SVG import.

### PR DESCRIPTION
**Pull request by derryx**
Hi!

This is my very rudimentary implementation of a color filter option for the SVG import which would help at least me to be able to keep cut and engraving stuff in one SVG file.

This is the first time I code C# so tell me if I do things the "non C# way".

CU
Thomas

### CODE REVIEW

**Comment by arkypita** [comment]
it does not work for me. test file here
colortest

**Comment by derryx** [comment]
Currently the code does only look at the stroke (the "outline") and not the fill color. We could change that of course.
So this version of your test file should work:
300974888-ad7b95b5-96a9-4e57-9144-356113e8ba6f

**Comment by derryx** [comment]
I changed the code to look for the fill color as well. Please check.

**Comment by falias4** [comment]
Nice feature 👍 

I noticed that this doesn't work when colors are set directly as attribute.
Maybe you find time to add this too, as it should be possible with relatively low effort.
```xml
// works
<rect style="fill:red;" />

// doesn't work
<rect fill="red" />
<rect stroke="red" />
```

*PS: It's also not working if the style is set with a class. But that's probably out of scope.* 😉

**Comment by derryx** [comment]
> Nice feature 👍
> 
> I noticed that this doesn't work when colors are set directly as attribute. Maybe you find time to add this too, as it should be possible with relatively low effort.
> 
> ```
> // works
> <rect style="fill:red;" />
> 
> // doesn't work
> <rect fill="red" />
> <rect stroke="red" />
> ```
> 
> _PS: It's also not working if the style is set with a class. But that's probably out of scope._ 😉



> Nice feature 👍
> 
> I noticed that this doesn't work when colors are set directly as attribute. Maybe you find time to add this too, as it should be possible with relatively low effort.
> 
> ```
> // works
> <rect style="fill:red;" />
> 
> // doesn't work
> <rect fill="red" />
> <rect stroke="red" />
> ```
> 
> _PS: It's also not working if the style is set with a class. But that's probably out of scope._ 😉

Have a look at #2204.
To support CSS classes to define colors in SVG would need to have a CSS parser in place. I will not add that. ;-)
Inkscape does not use CSS classes I would assume and this is the primary tool to do SVGs for our purpose, right?

CU
Thomas

**Comment by falias4** [comment]
@derryx Very cool. Thanks!

Parsing the CSS is definitely a bigger task. ^^
Just wanted to point it out in case of future "bug reports" because their SVGs are simply not based on an Inkscape design.

**Comment by arkypita** [comment]
I am having issues with very simple files: no gcode generated or crashes.
Can you test it? 
[LaserGRBL-logo.zip](https://github.com/arkypita/LaserGRBL/files/14487886/LaserGRBL-logo.zip)

**Comment by derryx** [comment]
> I am having issues with very simple files: no gcode generated or crashes. Can you test it? [LaserGRBL-logo.zip](https://github.com/arkypita/LaserGRBL/files/14487886/LaserGRBL-logo.zip)

I have a look. Should be no big issue.

**Comment by derryx** [comment]
Well actually this has nothing to do with color filtering. There is an exception inside the conversion code. 
crash-lasergrbl

**Comment by arkypita** [comment]
Not sure if it is something in code you have changed, or it was in the original algorithm too

**Comment by derryx** [comment]
I think the SVG file has errors because obviously incrementing by 2 is necessary because you always have X,Y coordinates. This seems not be the case in the given file.

**Comment by arkypita** [comment]
Thank you for your feedback, and sorry for bothering you. Actually these SVGs come from a program other than Inkscape (with which I've never had problems).

I tried to delve deeper into the problem.
The original .svg code, where the problem occurs, is a line element described as follows:

`l1.6-2.63,3.08.06`

I tried to re-save the with Inkscape, and the equivalent code but generated by Inkscape is the following:

`l 1.6,-2.63 3.08,0.06 `

It seems like the original code is more compressed/optimized, but my parser can't handle it. Probably a small change to a regex could be enough to fix the problem, but I have to understand well and verify that there are no side-effects.

**Comment by derryx** [comment]
Hi!

You are welcome. Here you find the official testsuite for SVG from W3C:
https://github.com/w3c/svgwg/wiki/Testing

I am pretty sure there is more nasty stuff lurking. ;-)

CU

Am Di., 5. März 2024 um 11:48 Uhr schrieb arkypita ***@***.***

**Pull request merged**
