### PR TITLE
Smoothie improvement

### PR DESCRIPTION
**Pull request by guillaume-rico**
Add spindle speed for G2 G3 command
Remove the possibility to send $X command

There is an improvements to be made. But I don't know how to do it... Remove Unlock button and menu :  
image
It may be better to open an issue for this enhancement ?

### CODE REVIEW

**Comment by arkypita** [comment]
> Remove Unlock button and menu

Done!

Also I have done some refactoring follow this guidelines:

- Avoid using of `(Firmware)Settings.GetObject("Firmware Type", Firmware.Grbl)` and prefer using `Core.Type` when available.

Switching from grbl to smoothie and vice-versa needs a restart of application due to mayor difference between them. `Core.Type` comes from the actual instance, not from configuration, and it is changed only after restart of application.

- Prefer implementing difference between grbl and smoothie communication protocol inside class `GrblCore` and `SmoothieCore`. If you are friendly with OOP this could be done with `virtual` and `overrides`.

Finally i have created a wiki page to give some help to who want to use LaserGRBL with smoothie.
Since I don't have direct experience feel free to write some hint on how to configure smoothie and LaserGRBL to put them in communication (if you want!).

https://github.com/arkypita/LaserGRBL/wiki/Smoothie-firmware

**Comment by guillaume-rico** [comment]
Nice ! I will update the wiki ASAP.

Marlin firmware can also be flashed on my board. If you want, I can work on
it.

**Comment by arkypita** [comment]
> Marlin firmware can also be flashed on my board. If you want, I can work on
it.


It would be great.

If you want to do some work in this direction, keep in mind that LaserGRBL was written "freehand" so without too much planning behind it, and without the virtuality necessary to manage different firmware (streamer, way to connect/reset, know the position etc) and without any ability to manage variations on the generated GCode (different laser on-off procedure etc).

In few words it was hard-coded to GRBL rules and convention.

When the Smoothie developers told me that Smoothie is "almost" grbl compatible, I start creating a "[SmoothieCore](https://github.com/arkypita/LaserGRBL/blob/master/LaserGRBL/SmoothieCore.cs)" class that could manage the few **communication/protocol** difference between grbl and smoothie.

Please note: communication difference, not difference in GCODE generation/parsing and preview rendering.

If you feel comfortable with inheritance/override syntax you can see that I remap only very few features.

In my head all the differences between two different firmware should be managed by GrblCore virtual functions, remapped in derived classes.

For example, if a firmware manages the reset, and another firmware does not manage it, the best thing is to put a property in get UIShowResetButton in the GrblCore class and remap it to return false in cases where the fw does not manage the reset.

In the same way if a firmware needs a certain command to reset the board, and another firmware needs another command, it is right to create a "SendBoardResetCommand" method and implement it differently in the two firmware (as I have done [here](https://github.com/arkypita/LaserGRBL/commit/b4d4481a052f982b0b4d81df397e3906f643bf5c) for example.

With this information you should be able to take the right steps. I'm working on creating a branch with a class for MarlinCore where you can handle all of this.

**Comment by arkypita** [comment]
Done a Marlin branch for this: https://github.com/arkypita/LaserGRBL/tree/Marlin

**Comment by guillaume-rico** [comment]
Great!
I will do my best to use virtual functions in derivated classes. Don't
hesitate to tell me if I don't respect coding standards. (I am not a
professional developer)

**Comment by arkypita** [comment]
Yep! The rule is: prefer concentrate the difference in virtual funcions of a class instead of spreading them in the code with a series of "if else if" in many places.

**Pull request merged**
