### PR TITLE
Updated slovak translation

### PR DESCRIPTION
**Pull request by vschindler**
Updated slovak translation

### CODE REVIEW

**Comment by arkypita** [comment]
Hi @vschindler and thanks for your contribution.
Maybe I am wrong because I am not very expert of github system but look like you create the pull request in a wrong direction.

image

I think that the correct way to submit translation/code change is to fork your own copy of LaserGRBL and make your own branch (optional) than create pull request from your master/branch to arkypita/LaserGRBL:master

Like this:

image

However i have received slovak translation also from another user #851 and I think i'll import his file.

**Comment by vschindler** [comment]
OK I would like to participate on the slovak translation.
Upload his then I download the source and check it out.
Then would try to create branch and pull request.
Thank you

**Comment by arkypita** [comment]
> OK I would like to participate on the slovak translation. Upload his then I download the source and check it out. Then would try to create branch and pull request. Thank you

You are welcome.

This morning I have included slovak update from the other user into master branch.
You can branch from master and pull a merge request if you have refine to suggest.

Have a nice day

**Comment by vschindler** [comment]
Hi arkypita,

thank you. I will correct some string coz the guy did a lot of mistakes.
When I try to open file GrblConfig.resx an error occurs

[image: obrázok.png]
Can you check it please ?

Same with file PreviewForm.resx
Thank you.
Best regards
V. Schindler

**Comment by arkypita** [comment]
> When I try to open file GrblConfig.resx an error occurs

What kind of error? Can you paste a screenshot in github? (attach image to email replay does not work in github).

**Comment by vschindler** [comment]
you did not received image in the mail ?
if not i uploaded it here
https://drive.google.com/open?id=0B5Cad80C85zBcWhpZTluWlV1RUNJV3FxN0Nzb3pNM3Qya0h3

**Pull request closed without merging**
