### PR TITLE
Optimizer consider both ending of curves

### PR DESCRIPTION
**Pull request by HomineLudens**
- Calculate travel distance for both start and end of a curve
- In case the ending is shorter, reverse the curve
- Remove Sqrt from distance calculation to speed up

### CODE REVIEW

**Comment by HomineLudens** [comment]
I can't test on hardware before some days.

**Comment by arkypita** [comment]
The result is very good! I tested with an Arduino board with GRBL firmware and it can be seen that the order of travel now follows a sense that appears logical even looking at it.

Furthermore, both by filling horizontal, vertical and diagonal, the same execution times are obtained.
In some cases the execution time is even halved (compared with the non-optimized). All this confirms the goodness of the algorithm.

Here are some numbers:
- horizontal: 65sec (unoptimized) 68sec (old algorithm)
- vertical: 93sec (unoptimized) 65sec (old algorithm)
- diagonal: 105sec (unoptimized) 65sec (old algorithm)
- **new algorithm, all direction: 49sec**

I also thought that the algorithm could decide to reverse the direction of travel of some segments, but I thought it would be too complicated to achieve (while you did it!) so I proceeded to generate the lines with a change of direction, so that the end of a segment find the beginning of another segment next to it.

I don't know if this thing of inverting segments is really necessary, more than anything else it only works with lines because when done on G2 / G3 curves it generates unexpected results.

image

For now, I call the new Optimize only on filling segments (which is 100% lines) and keep calling the old version of function for the edge pass.

**Comment by HomineLudens** [comment]
As you find out I didn't test the reverse of path with curved lines 😅
Probably the A and B control point of the curve must be flipped geometrically, not only swapped. 
I'll check it later!

**Comment by arkypita** [comment]
I actually think the idea of reversing paths is not a good idea at all. I mean, isn't it that when you decide to reverse a path, the initial data of the problem change so you should re-consider all the combinations?

I've done some tests with the diagonal cross fill, and the result looks crazy.

image

If instead I disable the calculation on the final point distance (by set `distancesB[p1, p2] = double.MaxValue;`) and consequently the possibility that it reverses the segment, the result seems much more intuitive and correct.

image

**Comment by arkypita** [comment]
I transferred the code to the master and published a new pre-release, so as to make this version easily testable.

**Comment by HomineLudens** [comment]
How do you enable G2 arc interpolation? 
I was expecting reversing as necessary, choosing the final point should force you to travel the segment backwards, but maybe I've oversimplify the problem. Need more test.

**Comment by arkypita** [comment]
Did you switch on "Smoothing" flag? I think that Potrace is not producing arcs without "smoothing" flag.

image

**Pull request merged**
