### PR TITLE
CustomButton Improvements

### PR DESCRIPTION
**Pull request by falias4**
1. Optional caption under image
    - Length of text is limited by the width of the image
2. Reorder with visual effect
    - Blue line where the new position will be
    - mouse at first half of image = insert before, other half = insert after
3. Clickable URL in edit dialog
2020-04-13 19_10_38-LaserGRBL v3 1 6

### CODE REVIEW

**Comment by arkypita** [comment]
sounds good

**Comment by arkypita** [comment]
I try your code. Very good Job!
There is only a small issue: when the drag action is aborted because it end outside button area the blue bar is not removed.

**Comment by arkypita** [comment]
fixed, also add dispose of graphic objects created with CreateGraphic

**Comment by falias4** [comment]
Thanks for the quick test and fixes :-)
Good point with the graphics dispose.
I noticed the issue with the aborted drag action but left it, because I thought it's a general issue (click animations keep the clicked state too).

**Comment by arkypita** [comment]
>I noticed the issue with the aborted drag action but left it, because I thought it's a general issue (click animations keep the clicked state too).

Oh thanks. I had never noticed it.
This is because I usually debug third-party code more than the code I write myself!

**Comment by arkypita** [comment]
I realized that the problem is due to a conflict between the standard button operations (mouse down, mouse up, and click) and the drag-drop operations on the same.

When you press the mouse on a button you have a mouse down event, when you release it (even if the mouse is now out of the button) you have a mouse up event, but if during this phase a drag-drop operation is launched (that is what I do) mouse down and click events are canceled for the object.

I believe that the button reordering operation should be activated as an alternative to their usability, with a "unlock buttons" mode that disables them from click and makes them reordeable.

**Comment by arkypita** [comment]
This would also prevent one from inadvertently performing custom button action while reordering buttons.

**Comment by falias4** [comment]
> This is because I usually debug third-party code more than the code I write myself!

I guess every programmer can relate to that :D

Locking the buttons sounds like a good idea. Especially because of the PushButton, that can't be dragged without executing the action.

**Pull request merged**
