### PR TITLE
Optimize the travel optimizer

### PR DESCRIPTION
**Pull request by Effer**
Avoid iterate all starting points, just start from the first one.

### CODE REVIEW

**Comment by arkypita** [comment]
Hello @HomineLudens 
I need your help again :-)

I went to implement a "vector filling" mechanism that is added next to the vector paths generated by potrace, generating a series of lines (left-to-right, alternated with right-to-left) and calculating the intersection with the potrace paths.

The result is very good, but obviously the laser traverses the entire lines.

image

Of course I wanted to try sending these lines to the "OptimizePaths" function with the algorithm you wrote.
This is the result I have.

image

I believe that the current algorithm is convinced that the start-point and the end-point of a path are coincident.
On the other hand, in the case of these generated segments, the exit point is different from the entry point.

I think the algorithm could do much better if it considered input and output separately.
This is the best result I think I can achieve (green-fluo lines highlight the best route).

image




These are the starting image and the options I used to accomplish this.

ras

image

image

**Comment by arkypita** [comment]
Any hint of how to change the algorithm to obtain this result?

**Comment by HomineLudens** [comment]
Hi! I'll try to give a look later. I'll be more then happy to contribute again.

**Comment by HomineLudens** [comment]
You was right, the algorithm works way better considering both possible ending for travel optimization.
It use more memory but should not be a problem. I've also found that I can get rid of some expansive Sqrt that should compensate the doubling of calculations.

GCode seems quite good
image

I can clean up the code and make a pull request later.

**Comment by arkypita** [comment]
You re the best!
What is the tool you use to draw the preview?

**Comment by HomineLudens** [comment]
Pull requested: https://github.com/arkypita/LaserGRBL/pull/1246 , I've use the Optimize Branch. I didn't test on hardware.

The tool in the screenshoot is [Camotics]( https://camotics.org/ ), it's a nice tools to simulate CNC path for 3d works. I've used an old version but I believe the project is still active even if not as active as your :D

**Comment by arkypita** [comment]
Great job! I'll give you a feedback ASAP.

I don't know if you noticed, but since when work with too many paths the algorithm sits down and takes too long, I made a version that takes advantage of C# parallel task.

It's nothing magical, it breaks the work into multiple sub-parts and runs OptimizePath on a small number of elements.
In the end the result isn't as optimized as running across the whole list, but it's still very good (and much more fast).

**Comment by HomineLudens** [comment]
Didn't notice the Parallel split, but yup, it should give  a better overall user experience. 
More investigation on the input to process could highlight other ways to boost the algorithm. 
But generally it's a matter of accuracy vs speed.

**Pull request merged**
