### PR TITLE
New "Click and Go" feature.

### PR DESCRIPTION
**Pull request by BeatSlayer**
Left click on the preview to execute a G1, with the current set feedrate, to that position and right click to execute a G0.

### CODE REVIEW

**Comment by BeatSlayer** [comment]
As requested in #959

**Comment by arkypita** [comment]
Hello @BeatSlayer 
I have seen that you are making a lot of new features. As soon as I can (weekend) I check and complete them. In the meantime, thanks.

**Comment by arkypita** [comment]
This code assumes to have always and only positive coordinates, in reality LaserGRBL is able to work with images positioned in each quadrant.

image

This code needs to be reviewed before it can be implemented in the trunk version.

**Comment by arkypita** [comment]
> This code needs to be reviewed before it can be implemented in the trunk version.

Don't worry. I am going to implement this feature by myself

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/releases/tag/v3.8.7

**Comment by arkypita** [comment]
Implemented by using double click

**Pull request closed without merging**
