### PR TITLE
Modern jog Control

### PR DESCRIPTION
**Pull request by Sardau**
replacing the old 'jog' control with a modern looking 
capture
custom Usercontrol.

It replace the direction and home button. It also replace the distance trackbar.

### CODE REVIEW

**Comment by Sardau** [comment]
Hello,

the jog control color use the system Highligth Color for the "icons" and Circle color can be configured with the control ForeColor property..

Ferretti Fabio

**Comment by arkypita** [comment]
I love this contribution

**Comment by arkypita** [comment]
Although I appreciate the control you developed for LaserGRBL I and other users have encountered some difficulties and problems with it.

The first problem is that with the removal of the "jog step slider" control all the other jog modes (keyboard direction keys, custom buttons) no longer have the step values to refer to, and therefore no longer work correctly. .

Furthermore the control is difficult to use with the touchscreen.

For these reasons I believe I will have to go back to the previous version.

**Comment by Sardau** [comment]
Hello,

 

I understand, I’ve had the same problem with touchscreen. But I was trying to limit amount of modification by introducing the control, so it was easier for you to see what was changing and assess the risk of using it.

 

In the version I use, I’ve double the size of the control by reducing the size of the listbox upside and enlarge it, it work better with tablet  and smaller resolution netbook (1024x768) with touchpad but the preview panel is much smaller.

 

Have a nice day

Ferretti Fabio

**Comment by arkypita** [comment]
I am going to implement something like "continuos jog" so jog can continue until your release the button, so distance/step is no longer needed.

Try the latest commit.

**Comment by arkypita** [comment]
(master commit not released version)

**Pull request merged**
