### PR TITLE
Filler and Outliner

### PR DESCRIPTION
**Pull request by vniacob**
Two new actions to touch raster images:
- filling in black/white (left/right mouse button) parts of image
- automatically outline an image to delineate a border, useful to have cutting outline
LaserGRBL_lgFmwmrGTV
LaserGRBL_NP3ypmg7a5

### CODE REVIEW

**Comment by arkypita** [comment]
Hi @vniacob Vito
Sounds a good idea but I have found huge CPU consumption and issues when using this tool.
Moreover it works well with small files, but it is very slow if used on a big file.

image

image

**Comment by arkypita** [comment]
Here is the file I am testing with
[testfile.zip](https://github.com/arkypita/LaserGRBL/files/8837264/testfile.zip)

**Comment by vniacob** [comment]
I think the problem is in the "pixel by pixel" manipulation (methods "Fill4" and "Ouline" in ImageTransform.cs) that take a lot of time on big images... but I don't know how to do it in other way... in java I would use threads, in C# I don't know how to use threads... :(

**Comment by arkypita** [comment]
it is not so much for the thread as because the .NET GetPixel method is not optimized and is very slow. there is a way to access the bitmap faster but i am not familiar with it.

https://stackoverflow.com/questions/24701703/c-sharp-faster-alternatives-to-setpixel-and-getpixel-for-bitmaps-for-windows-f
https://www.google.com/search?q=c%23+fast+getpixel

**Comment by vniacob** [comment]
Interesting... I will check it...

**Comment by vniacob** [comment]
Ok, Checked and optimized.
I tested your testfile and now is very fast.

**Comment by vniacob** [comment]
Any news for this request?

**Comment by arkypita** [comment]
I know it sounds like an excuse, but I've had very little time in this period. I need to fully verify everything because as soon as I publish a release if there is even the smallest problem, people start storming with reports and I have to rush to fix things.

I think I will not struggle to include this change soon, while that of the layers (which is more invasive) will still need some time.

**Comment by arkypita** [comment]
Accept pull request and testing

**Pull request merged**
