### PR TITLE
Fix some forms icons

### PR DESCRIPTION
**Pull request by Effer**
Some forms were missing LaserGRBL icon and use the default one.
Unfortunatly I don't have VS2012 installed and so I had to adjust some files by hands to avoid conflicts in the solution.

BTW thanks for share the code and software. Great Job.

### CODE REVIEW

**Comment by arkypita** [comment]
thanks for sharing you fix

Please note that GoingToV3 is a development branch that is not production ready (raster import not working now).

**Comment by Effer** [comment]
my pleasure

If you prefer I can push to the master also. 
I'd like to contribute with some other feature, where is the best place to push them?

**Comment by Effer** [comment]
Sorry to bump @arkypita , where the best place to PR? Master or V3?

**Comment by arkypita** [comment]
Master is the best place, however i currently working both on master (with minor changes) and on V3 doing a huge code refactoring.

Due to merging trouble between this two branch I prefer (for now) to not receive code from contributor. I will be happy to receive push from other user as soon as I have completed this job

thanks

**Comment by Effer** [comment]
Got it. I'll keep a look on the project. I just made some little changes to optimize the output from raster.
Here is before:
image

and after:
image

You can notice the reduction of G0 traveling and so less time spent waiting the laser head move around doing nothing.

Good job for your refactoring.

**Comment by arkypita** [comment]
This sound very good! How did you get it? Did you implement something complex like a "travelling salesman algorithm" or did you use a simple trick?

However, i see you are Italian like me.
If you need/want to talk about lasergrbl in italian you can mail me using info chiocciola lasergrbl punto com

**Comment by Effer** [comment]
Thanks! Is a simple approach to solve TSP that give good result without overburden the project with external dependencies and big libraries.

It will be a pleasure to speak native. Wait for my email.

**Pull request merged**
